import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MesloLGL Nerd Font"

[window]
decorations = "none"

[window.padding]
x = 4
y = 4
