import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MesloLGL Nerd Font"

[window]
decorations = "Buttonless"

[window.padding]
x = 4
y = 4

# for macs that use zsh as default
[shell]
program = "/usr/local/bin/bash"
args = ["-l"]
