set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'prabirshrestha/vim-lsp'
Plugin 'nanotech/jellybeans.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" Put your non-Plugin stuff after this line

if executable('intelephense')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'intelephense',
        \ 'cmd': {server_info->['intelephense', '--stdio']},
        \ 'allowlist': ['php', 'phtml'],
        \ 'root_uri': {server_info->lsp#utils#path_to_uri(
        \	lsp#utils#find_nearest_parent_file_directory(
        \		lsp#utils#get_buffer_path(),
        \		['.git/']
        \	))},
        \ 'workspace_config': {
        \   'intelephense': {
        \       'environment': {
        \           'phpVersion': "8.2",
        \       },
        \   },
        \ },
        \})
endif

function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gs <plug>(lsp-document-symbol-search)
    nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)
    "nnoremap <buffer> <expr><c-f> lsp#scroll(+4) todo: not working
    "nnoremap <buffer> <expr><c-F> lsp#scroll(-4) todo: not working

    let g:lsp_format_sync_timeout = 1000
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

syntax on

" set path+=** TODO: remove if unnecessary
set wildmenu
set clipboard=unnamed
set expandtab
set tabstop=4
set autoindent
set scrolloff=8
set sidescrolloff=8
set number
set relativenumber
" Display extra whitespace
set list
set listchars=tab:»·,trail:·
set showcmd

set backupdir=$HOME/.vim/tmp
set directory=$HOME/.vim/tmp " Don't clutter my dirs up with swp and tmp files
set undodir=$HOME/.vim/undo
set undofile

let mapleader=","
let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files -co --exclude-standard']
nmap k gk
nmap j gj

colorscheme jellybeans
packadd! editorconfig
